{
    'name': 'Ventorix Global Trade Theme',
    'description': 'B2B industrial theme for Ventorix Global Trade — flanges, pipes, valves, fittings, and industrial materials.',
    'category': 'Theme/Creative',
    'version': '18.0.1.0.0',
    'author': 'Ventorix Global Trade',
    'license': 'LGPL-3',
    'depends': ['theme_common', 'website'],
    'data': [
        'data/generate_primary_template.xml',
        'data/ir_asset.xml',
        'views/layout.xml',
        'views/snippets/s_vx_hero.xml',
        'views/snippets/s_vx_categories.xml',
        'views/snippets/s_vx_about.xml',
        'views/snippets/s_vx_process.xml',
        'views/snippets/s_vx_china_partner.xml',
        'views/snippets/s_vx_certifications.xml',
        'views/snippets/s_vx_cta.xml',
        'views/snippets/s_vx_contact.xml',
        'views/snippets/s_vx_catalog.xml',
        'views/snippets/snippets_registry.xml',
        'views/pages.xml',
        'data/website_menu_data.xml',
    ],
    'images': [
        'static/description/banner.png',
    ],
    'post_init_hook': '_post_init_hook',
    'application': False,
    'auto_install': False,
    'installable': True,
}
